# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ release/* ]

env:
  Stack_Name: dev # TODO get stack from branch name
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2
    
    - name: Install Global npm
      working-directory: az-drunk-Global
      run: npm install
    
    - name: Pulumi CLI Action
      uses: pulumi/actions@v3.15.0
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      with:
        # Pulumi command to run, eg. up
        command: up
        # Which stack you want to apply to, eg. dev
        stack-name: ${{ env.Stack_Name }}
        # Location of your Pulumi files. Defaults to ./
        work-dir: az-drunk-Global
      
